kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-backend
  namespace: todo-app
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: sherifemad21/todo-app-backend:last-version2
        resources:
          requests:
            memory: 200M
            cpu: 100m
          limits:
            memory: 500M
            cpu: 200m
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: todo-app
spec:
  selector:
    app: todo-backend
  ports:
  - port: 8080
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-backend-ingress
  namespace: todo-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: todo-backend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: todo-app.local
    http:
      paths:
      - pathType: Prefix
        path: "/api/backend"
        backend:
          service:
            name: todo-backend
            port: 
              number: 8080
  tls:
    - hosts: 
      - todo-app.local
      secretName: tls-secret
