kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-frontend
  namespace: todo-app
  labels:
    app: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: todo-frontend
        image: sherifemad21/todo-app-frontend:test-argo-arm
        resources:
          requests:
            memory: 50M
            cpu: 50m
          limits:
            memory: 100M
            cpu: 100m
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: todo-app
spec:
  selector:
    app: todo-frontend
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-frontend-ingress
  namespace: todo-app
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    name: todo-frontend-ingress
spec:
  # ingressClassName: nginx
  rules:
  - host: todo-app-frontend.local
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: todo-frontend
            port:
              number: 80
  tls:
  - hosts:
    - todo-app-frontend.local
    secretName: tls-secret



